<!DOCTYPE bancos[ 
       <!ELEMENT bancos (banco)+>
       <!ELEMENT banco (parametro1, parametro2, parametro3, parametro4)>
       <!ATTLIST banco id ID #REQUIRED>
       <!ELEMENT parametro1 (#PCDATA)>
       <!ELEMENT parametro2 (#PCDATA)>
       <!ELEMENT parametro3 (#PCDATA)>
       <!ELEMENT parametro4 (#PCDATA)>
]>

<bancos>
	<banco id="BBVA">
		<parametro1>BBVA1111111</parametro1>
		<parametro2>BBVA2222222</parametro2>
		<parametro3>BBVA3333333</parametro3>
		<parametro4>BBVA4444444</parametro4>
	</banco>
	<banco id="BANCOLOMBIA">
		<parametro1>BanColombia1111111</parametro1>
		<parametro2>BanColombia2222222</parametro2>
		<parametro3>BanColombia3333333</parametro3>
		<parametro4>BanColombia4444444</parametro4>
	</banco>
</bancos>


<!-- <properties> -->
<!-- 
	Agregar a la lista solo los nombres de atributos de la clase de lo contratio arroja
	'java.lang.Class.getDeclaredField'
-->
<!-- <entry key="parameter1">nombre</entry> -->
<!-- <entry key="parameter2">telefono</entry> -->
<!-- <entry key="parameter3">email </entry> -->




<!-- </properties> -->